syntax match Keyword          "from"
syntax match Keyword          "to"
syntax match Keyword          "or"
syntax match Keyword          "and"
syntax match Keyword          "not"
syntax match Conditional      "if"
syntax match Conditional      "then"
syntax match Conditional      "else"
syntax match Conditional      "=>"
syntax match Function       /\\$\([A-Z]\+\)/
syntax match Function       /\([A-Z]\+\)/
